package clean.architecture.omdb.data.local.entity

import org.springframework.data.annotation.Id
import org.springframework.data.relational.core.mapping.Column
import org.springframework.data.relational.core.mapping.Table
import java.time.Instant
import java.time.LocalDate

/**
 * Represents search entity in a database.
 *
 * @param id the primary key auto-generated by a database.
 * @param query the unique search query.
 * @param updatedDate the date when movies were loaded/refreshed.
 * @param lastSeenAt the exact moment when the user last searched/viewed it.
 */
@Table("search_history")
data class SearchEntity(
    @Id
    @Column(value = "id") val id: Int? = null,
    @Column(value = "query") val query: String,
    @Column(value = "updated_date") val updatedDate: LocalDate,
    @Column(value = "last_seen_at") val lastSeenAt: Instant
)
