spring.config.import=optional:secrets.properties
omdb.base-url=https://www.omdbapi.com
# omdb.api-key should be set in "secrets.properties"

spring.application.name=clean-architecture
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=debug
logging.level.org.springframework.r2dbc=DEBUG
spring.mvc.problemdetails.enabled=true
spring.webflux.problemdetails.enabled=true
spring.sql.init.mode=always
