package concept.stc.data.local.entity

import org.springframework.data.annotation.Id
import org.springframework.data.relational.core.mapping.Column
import org.springframework.data.relational.core.mapping.Table

/**
 * Represents "search to movies" many-to-many reference.
 * Every search can have multiple movies.
 * One movie can be referenced by multiple searches.
 *
 * @param id the primary key auto-generated by a database.
 * @param searchId the search id.
 * @param movieId the movie id.
 */
@Table("search_movies")
data class SearchToMovieReference(
    @Id
    @Column(value = "id") val id: Int? = null,
    @Column(value = "search_id") val searchId: Int,
    @Column(value = "movie_id") val movieId: Int
)
